apiVersion: apps/v1
kind: Deployment
metadata:
  name: houseofpizza-deployment
  labels:
    app: houseofpizza
spec:
  replicas: 2  # Number of replicas
  selector:
    matchLabels:
      app: houseofpizza
  template:
    metadata:
      labels:
        app: houseofpizza
    spec:
      containers:
        - name: houseofpizza
          image: jakino/houseofpizza:latest  # Ref image Docker
          ports:
            - containerPort: 80  # Port of container
          envFrom:
            - configMapRef:
                name: be-config

---
apiVersion: v1
kind: Service
metadata:
  name: houseofpizza-service
spec:
  selector:
    app: houseofpizza
  ports:
    - protocol: TCP
      port: 80  # Port on which the service will be displayed
      targetPort: 80  # Internal pod port
      nodePort: 30008
  type: NodePort  # Tipe of service (ClusterIP, NodePort, ecc.)