services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./postgres/create-schema.sql:/docker-entrypoint-initdb.d/create-schema.sql
    env_file:
      - .env
