services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=houseofpizza
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - ./postgres/create-schema.sql:/docker-entrypoint-initdb.d/create-schema.sql
