# How to install Jenkins using Ansible Version 2018
# https://awsbloglink.wordpress.com/2018/10/08/how-to-install-jenkins-using-ansible-version-2018/
---
- name: Configuration master
  hosts: all
  gather_facts: false
  become: yes
  
  tasks:
    - include_vars: config_vars.yml

    - debug: msg="Hello, {{ master }}!"

    - debug: msg="Hello kubeadm_token, {{ kubeadm_token }}!"

    - debug: msg="Hello ip_address, {{ ip_address }}!"

    - debug: msg="Hello cluster_name, {{ cluster_name }}!"

    - debug: msg="Hello aws_region, {{ aws_region }}!"

    - debug: msg="Hello aws_subnets, {{ aws_subnets }}!"

    - debug: msg="Hello aws_subnets, {{ aws_access_key }}!"

    - debug: msg="Hello aws_subnets, {{ aws_secret_access_key }}!"

    - name: Creates directory aws credential
      ansible.builtin.file:
        path: /home/ubuntu/.aws
        state: directory
  
    - name: Add aws_access_key file
      copy:
        dest: "/home/ubuntu/.aws/aws_access_key"
        content: |
          {{ aws_access_key }}
  
    - name: Add aws_secret_access_key file
      copy:
        dest: "/home/ubuntu/.aws/aws_secret_access_key"
        content: |
          {{ aws_secret_access_key }}

    - name: Execute the Uptime command over Command module
      register: uptimeoutput
      command: "uptime"

    - debug:
        var: uptimeoutput.stdout_lines
  
    - name: Install AWS CLI client
      block:
        - name: Download AWS CLI
          shell: "curl -o awscliv2.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        
        - name: Install unzip
          apt:
            name: unzip
            state: present
        
        - name: Extract AWS CLI
          shell: "unzip awscliv2.zip > /dev/null"
        
        - name: Run AWS CLI installer
          shell: "sudo ./aws/install"
      tags: 
        - aws_cli
  
    - name: Tag subnets
      block:
        - name: Tag subnets
          shell: "for SUBNET in {{ aws_subnets }}; do aws ec2 create-tags --resources $SUBNET --tags Key=kubernetes.io/cluster/{{ cluster_name }},Value=shared --region {{ aws_region }}; done"
      tags:
        - tag_subnets

    - name: Install Containerd
      block:
        - name: Disable swap
          command: "swapoff -a"
        
        - name: Configure kernel modules and sysctl
          command: "modprobe overlay && modprobe br_netfilter"
        
        - name: Configure sysctl
          copy:
            dest: "/etc/sysctl.d/kubernetes.conf"
            content: |
              net.bridge.bridge-nf-call-ip6tables = 1
              net.bridge.bridge-nf-call-iptables = 1
              net.ipv4.ip_forward = 1
        
        - name: Configure modules load
          copy:
            dest: "/etc/modules-load.d/k8s.conf"
            content: |
              overlay
              br_netfilter
        
        - name: Apply sysctl settings
          command: "sysctl --system"

    # Update apt cache
    - name: Update apt cache
      apt:
        update_cache: yes

    # Install required packages
    - name: Install required packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
        state: present

    # Create Docker keyring directory
    - name: Create Docker keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    # Add Docker GPG key
    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

     # Get system architecture
    - name: Get system architecture
      command: dpkg --print-architecture
      register: architecture

    # Get OS codename
    - name: Get OS codename
      command: bash -c 'source /etc/os-release && echo $VERSION_CODENAME'
      register: codename

    # Add Docker repository to apt sources list
    - name: Add Docker repository to APT sources
      copy:
        content: "deb [arch={{ architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ codename.stdout }} stable"
        dest: /etc/apt/sources.list.d/docker.list
        mode: '0644'

    # Update apt cache again
    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    # Install containerd
    - name: Install containerd
      apt:
        name: containerd.io
        state: present

    # Create containerd config directory
    - name: Create containerd config directory
      file:
        path: /etc/containerd
        state: directory

    # Configure containerd
    - name: Generate containerd config
      shell: |
        containerd config default | tee /etc/containerd/config.toml

    # Restart and enable containerd service
    - name: Restart and enable containerd
      systemd:
        name: containerd
        enabled: yes
        state: restarted

    # Enable IP forwarding
    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    
    ########################################
    # Install Kubernetes components
    ########################################

    # Add Kubernetes GPG key
    - name: Download Kubernetes GPG key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        mode: '0644'

    # Add Kubernetes repository to apt sources
    - name: Add Kubernetes repository
      copy:
        content: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /'
        dest: /etc/apt/sources.list.d/kubernetes.list
        mode: '0644'

    # Update apt cache after adding Kubernetes repo
    - name: Update apt cache after adding Kubernetes repo
      apt:
        update_cache: yes

    # Install Kubernetes components
    - name: Install kubelet and kubeadm
      apt:
        name:
          - kubelet
          - kubeadm
        state: present

    # Enable bash completion for kubeadm
    - name: Enable bash completion for kubeadm
      shell: |
        kubeadm completion bash > /etc/bash_completion.d/kubeadm
      args:
        creates: /etc/bash_completion.d/kubeadm

    # Install kubectl manually
    - name: Download kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    # Enable and start kubelet service
    - name: Enable and start kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: started

    ########################################
    # Initialize Kubernetes Cluster
    ########################################

    - name: Remove containerd config for Kubernetes
      file:
        path: /etc/containerd/config.toml
        state: absent

    - name: Restart containerd after config reset
      systemd:
        name: containerd
        state: restarted

    - name: Reset kubeadm cluster
      command: kubeadm reset --force

    - name: Initialize Kubernetes cluster
      command: kubeadm init

    # Setup kubeconfig for ubuntu user
    - name: Create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0700'

    - name: Copy kubeconfig to user directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: '0600'